import "./terms-of-use.css";
function TermsOfUse() {
  return (
    <div className="terms-of-use-container">
      <br />
      <div style={{ textAlign: "left", direction: "ltr", marginLeft: "2vw" }}>
        <h1>Terms of Service</h1>
        <p>
          <em>Last Update January 9, 2020</em>
        </p>
        <p style={{ textAlign: "left", direction: "ltr" }}>
          PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICE (DEFINED BELOW)
          AND WEBSITE ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO
          ALL OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICE OR WEBSITE
          IN ANY MANNER.
        </p>
        <p style={{ textAlign: "left" }}>
          These Terms of Service (the “Terms”) are a binding contract between
          you and Cyber Pro Israel Ltd. (“Cyber Pro”, “we” “us” or “our”). By
          accessing or using the Service (defined below) in any way, or our
          website –{" "}
          <a href="https://cyberpro-israel.co.il/">
            https://cyberpro-israel.co.il/
          </a>
          , by executing an order form that references these Terms or by
          approving our price proposal that references these Terms, you
          acknowledge that you have read and understood and agree to comply with
          the terms and conditions below, and these Terms will remain in effect
          at all times while you use the Service or any data obtained through
          the Service or the Website.
        </p>
        <ol style={{ textAlign: "left" }}>
          <li>
            In these Terms the following terms have the meanings ascribed next
            to them:
            <ul>
              <li>
                <strong>Client</strong> or you means a legal entity which has a
                signed agreement or binding purchase order with Cyber Pro for
                the provision of Service to that entity.
              </li>
              <li>
                <strong>Client Data </strong>means any Personal Data and/or
                Non-Personal Data, as such terms are defined in our Privacy
                Policy available at{" "}
                <a href="https://cyberpro-israel.co.il/privacy-policy/">
                  https://cyberpro-israel.co.il/privacy-policy/
                </a>{" "}
                (“<strong>Privacy Policy</strong>”), or other information
                relating to the Client which is collected, processed, accessed
                or affected while providing the Service.
              </li>
              <li>
                <strong>Content </strong>means visual, audio, numeric,
                graphical, text or other data or content, which is displayed or
                made available through the Website or otherwise by us for use in
                conjunction with the Service, if any.
              </li>
              <li>
                <strong>Report/s</strong> mean any output or results of the
                Service provided to the Client or generated by the Client.
              </li>
              <li>
                <strong>Service </strong>means Cyber Pro’s SaaS platform which
                provides real-time attack surface analysis services by
                continuously stimulating sophisticated attackers actual
                reconnaissance and examination processes across live
                infrastructure and network assets. The Service is provided to
                each Client according to a specific proposal and remotely from
                the Cyber Pro’s premises or elsewhere, as Cyber Pro in its
                discretion may deem required or advisable.
              </li>
              <li>
                <strong>Website</strong> means our public website available at{" "}
                <a href="https://cyberpro-israel.co.il/">
                  https://cyberpro-israel.co.il/
                </a>{" "}
                providing marketing materials and professional information
                regarding our Service; for clarity, the term “Website” includes
                all Content (defined below) on the Website, but excludes the
                Service, unless otherwise specified herein.
              </li>
            </ul>
          </li>
          <li>
            <strong>Ability to Accept Terms</strong>. If you access and use the
            Service and/or the Website, you represent and warrant that you are
            of legal age and have the right and authority to enter into these
            Terms on your own behalf. If you are entering into these Terms on
            behalf of a company or other legal entity, you represent that you
            have the authority to bind such entity and its affiliates to these
            Terms, in which case the terms “you” or “your” shall refer to such
            entity and its affiliates.
          </li>
          <li>
            <strong>License to Website</strong>. Cyber Pro hereby grants you,
            and you accept, a non-exclusive, non-transferable,
            non-sublicensable, and fully revocable license to access and use the
            Website and Content, provided that you comply with these Terms and
            the restrictions herein.
          </li>
          <li>
            <strong>Nature of the Service</strong>.
            <ul>
              <li>
                Client agrees that Cyber Pro may use various techniques and
                software tools in connection with the Services, to which the
                Client hereby consents. Client acknowledges and agrees that
                Cyber Pro cannot and does not guarantee the results of the
                Service, its correctness or accuracy. To the extent required or
                deemed advisable by Cyber Pro and/or Client, Client will inform
                or confirm to third parties that Cyber Pro is conducting the
                Service with Client’s approval.
              </li>
            </ul>
          </li>
          <li>
            <strong>Client</strong> <strong>Responsibility</strong>. Client
            shall have sole responsibility for all adequate protection and
            backup of data and/or equipment used in connection with or having
            any connection to the Services. Client will not make any claim
            against Cyber Pro for lost data, re-run time, inaccurate output,
            work delays or lost profits resulting from the Service.
          </li>
        </ol>
        <p style={{ textAlign: "left" }}>
          You represent and warrant that: (i) you have obtained and will hold
          for the entire duration of the provision of the Service from the
          third-party owner (or licensor, as the case may be) of all products
          and services contained in Client’s systems or otherwise subject to the
          Service (including internet service providers and hosting suppliers),
          all approvals and permits required in order to make the Service not
          infringing on the rights (intellectual property or other) of such
          third party, including such third party’s information systems,
          network, and infrastructure and to the extent required, you have
          obtained appropriate consent from such third parties for the Services
          to be carried out; (ii) the Client Data and all other data you provide
          is lawful and non-infringing; and (iii) engaging Cyber Pro to perform
          the Service and any failure to use or access data contained in any
          Client’s systems as a consequence of the Service will not: (a)
          infringe on the intellectual property rights of any third party or any
          rights of publicity or privacy; (b) violate any law, statue, ordinance
          or regulation (including without limitation the laws and regulations
          governing export control, unfair competition, antidiscrimination or
          false advertising); (c) create or cause any damages, corruption, loss,
          interferences, security intrusions or any failure of any systems in
          your control, possession, or your business operations, or any systems
          of any third-party.
        </p>
        <ol style={{ textAlign: "left" }} start="6">
          <li>
            <strong>Restrictions</strong>. Except as expressly permitted in
            these Terms, you may not, and shall not allow any third party to:
            (i) give, sell, rent, lease, timeshare, sublicense, disclose,
            publish, assign, market, sell, display, transmit, broadcast,
            transfer or distribute any portion of the Service and/or the Website
            to any third party, including, but not limited to your affiliates,
            or use the Service in any service bureau arrangement; (ii)
            circumvent, disable or otherwise interfere with security-related
            features of the Website and/or Service or features that prevent or
            restrict use or copying of any content or that enforce limitations
            on use of the Service and/or Website; (iii) reverse engineer,
            decompile or disassemble, decrypt or attempt to derive the source
            code of, the Service and/or Website, or any components thereof; (iv)
            copy, modify, translate, patch, improve, alter, change or create any
            derivative works of the Service and/or Website, or any part thereof;
            (v) use any robot, spider, scraper or other automated means to
            access or monitor the Service and/or Website for any purpose; (vi)
            take any action that imposes or may impose (at Cyber Pro’s sole
            discretion) an unreasonable or disproportionately large load on the
            Cyber Pro’s infrastructure which supports the Website and/or
            Service; (vii) interfere or attempt to interfere with the integrity
            or proper working of the Service and/or Website, or any related
            activities; (viii) develop (alone or together with others) a service
            or product competing with the Service and/or Website; and (ix) use
            the Service and/or Website in any unlawful manner or for any
            harmful, irresponsible or inappropriate purpose, or in breach of
            these Terms. Without derogating from the above, you agree to be
            liable to Cyber Pro for any act or omission of any of your employees
            or anyone on your behalf using the Service or Website that would
            constitute a breach of these Terms as if such acts or omissions were
            performed by you.
          </li>
          <li>
            <strong>Security</strong>. Cyber Pro agrees to implement during the
            provision of the Service reasonable security measures to protect
            Client Data and will, at a minimum, utilize industry standard
            security procedures, as described in our Privacy Policy available at{" "}
            <a href="https://cyberpro-israel.co.il/privacy-policy/">
              https://cyberpro-israel.co.il/privacy-policy/
            </a>
          </li>
          <li>
            <strong>Links to Other Websites</strong>. The Website may provide
            links to the websites or services of other third-party sites. Links
            to such third-party sites do not constitute any endorsement by Cyber
            Pro of such third-party sites, or the quality, suitability or
            accuracy of the products, content, materials or information
            presented or made available by such sites. You acknowledge and agree
            that Cyber Pro, its directors, officers, employees, agents, service
            providers and representatives, other third parties, and each of
            their respective successors and assigns, are not responsible for any
            claims, damages or losses caused or alleged to have been caused by
            the use of any third-party sites, or from the products, content,
            material or information presented by or available through those
            sites.
          </li>
          <li>
            <strong>Intellectual Property</strong>.
            <ul>
              <li>
                <u>Website and Service</u>. Title and full, exclusive ownership
                rights in the Service and the Website (and all parts of either,
                including the Content), and all reproductions, corrections,
                modifications, enhancements and improvements, and all related
                patent rights, copyrights, trade secrets, trademarks, service
                marks, related goodwill, including reports and data related to
                your usage of the Website and/or Service (excluding Client
                Data), are the exclusive property of Cyber Pro. Through the
                Service, you do not obtain any rights in our technology or
                intellectual property. You will not remove, alter, or obscure
                any proprietary notices (including copyright notices) of Cyber
                Pro on any reports or on any aspect of the Service. Any
                suggestions, recommendations, improvements, inventions and
                feedback by you or by anyone on your behalf in connection with
                the Service, and other services, products or solutions of Cyber
                Pro are the sole property of Cyber Pro, irrespective of the
                creator.
              </li>
              <li>
                <u>Client Data</u>. The intellectual property and all other
                rights, title and interest of any nature in and to Client Data
                are and shall remain your exclusive property. Except as
                expressly set forth herein, nothing in these Terms shall be
                construed as transferring any rights, title or interests in
                Client Data to Cyber Pro or any third party.
              </li>
              <li>
                <u>Ownership of Report</u>. The intellectual property and all
                other rights, title and interest of any nature in and to the
                Report which is the outcome of the Service are and shall remain
                Cyber Pro’s exclusive property (excluding Client Data). Except
                as expressly set forth herein, nothing in these Terms shall be
                construed as transferring any rights, title or interests in such
                Report to you or any third party.
              </li>
            </ul>
          </li>
          <li>
            <strong>Confidential Information</strong>. You agree to keep
            confidential and to use only for purposes permitted under these
            Terms, any Cyber Pro proprietary or confidential information
            disclosed to you pursuant to these Terms or in connection with your
            use of the Service which is marked as confidential or is identified
            at the time of disclosure as confidential or which would reasonably
            be considered confidential or proprietary in nature. The obligation
            of confidentiality shall not apply to information which is publicly
            available through authorized disclosure, is rightfully known by you
            prior to the time of disclosure as evidenced in writing, is
            rightfully obtained from a third party who has the right to disclose
            it, or which is required by law, government order or request to be
            disclosed (provided that you shall give prior written notice to
            Cyber Pro of such disclosure and an opportunity, at Cyber Pro’s
            expense, to resist or restrain the scope of such order or request).
          </li>
          <li>
            <strong>Support</strong>. Email and web support is available Sunday
            through Thursday during our standard working hours. We will
            initially address support requests within one (1) business day. Our
            support services include reasonable commercial efforts to address
            any malfunction of the Service which is in our control.
          </li>
          <li>
            <strong>Privacy Policy</strong>. You acknowledge and agree that we
            will use any Personal Data that we may collect or obtain in
            connection with the Website and/or the Service in accordance with
            our Privacy Policy available at{" "}
            <a href="https://cyberpro-israel.co.il/privacy-policy/">
              https://cyberpro-israel.co.il/privacy-policy/
            </a>{" "}
            . Other than our security obligations under Section Except as
            expressly permitted in these Terms, you may not, and shall not allow
            any third party to: (i) give, sell, rent, lease, timeshare,
            sublicense, disclose, publish, assign, market, sell, display,
            transmit, broadcast, transfer or distribute any portion of the
            Service and/or the Website to any third party, including, but not
            limited to your affiliates, or use the Service in any service bureau
            arrangement; (ii) circumvent, disable or otherwise interfere with
            security-related features of the Website and/or Service or features
            that prevent or restrict use or copying of any content or that
            enforce limitations on use of the Service and/or Website; (iii)
            reverse engineer, decompile or disassemble, decrypt or attempt to
            derive the source code of, the Service and/or Website, or any
            components thereof; (iv) copy, modify, translate, patch, improve,
            alter, change or create any derivative works of the Service and/or
            Website, or any part thereof; (v) use any robot, spider, scraper or
            other automated means to access or monitor the Service and/or
            Website for any purpose; (vi) take any action that imposes or may
            impose (at Cyber Pro’s sole discretion) an unreasonable or
            disproportionately large load on the Cyber Pro’s infrastructure
            which supports the Website and/or Service; (vii) interfere or
            attempt to interfere with the integrity or proper working of the
            Service and/or Website, or any related activities; (viii) develop
            (alone or together with others) a service or product competing with
            the Service and/or Website; and (ix) use the Service and/or Website
            in any unlawful manner or for any harmful, irresponsible or
            inappropriate purpose, or in breach of these Terms. Without
            derogating from the above, you agree to be liable to Cyber Pro for
            any act or omission of any of your employees or anyone on your
            behalf using the Service or Website that would constitute a breach
            of these Terms as if such acts or omissions were performed by you.
          </li>
          <li>
            <strong>Security</strong>. Cyber Pro agrees to implement during the
            provision of the Service reasonable security measures to protect
            Client Data and will, at a minimum, utilize industry standard
            security procedures, as described in our Privacy Policy available at
            Cyber Pro agrees to implement during the provision of the Service
            reasonable security measures to protect Client Data and will, at a
            minimum, utilize industry standard security procedures, as described
            in our Privacy Policy available at , we assume no responsibility or
            liability for Client Data, and you shall be solely responsible for
            Client Data and the consequences of using, disclosing, storing, or
            transmitting it.
          </li>
          <li>
            <strong>Warranty and Disclaimer</strong>
            <ul>
              <li>
                Cyber Pro shall perform the Service on a reasonable commercial
                efforts’ basis, using reasonable skill and care.
              </li>
              <li>
                The WEBSite AND the Service Are provided on an “as is” and “as
                available” basis, and without warranties of any kind either
                express or implied. WE DO NOT WARRANT THAT THE SERVICE WILL MEET
                CLIENT’S REQUIREMENTS. CYBER PRO HEREBY DISCLAIMS ALL
                WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION,
                IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A
                PARTICULAR PURPOSE AND NON-INFRINGEMENT.
              </li>
              <li>
                CYBER PRO DOES NOT WARRANT THAT THE SERVICE OR ACCESS TO AND USE
                OF THE WEBSITE OR SERVICE WILL BE UNINTERRUPTED OR ERROR FREE,
                THAT ALL VULNERABILITIES AND DEFECTS WILL BE DETECTED, OR THAT
                THE WEBSITE OR SERVICE IS FREE FROM VIRUSES OR OTHER HARMFUL
                CODE.
              </li>
              <li>
                CYBER PRO OFFERS NO WARRANTY REGARDING THE RELIABILITY OF THE
                PERFORMANCE OF THE SERVICE, INCLUDING WITHOUT LIMITATION ANY
                WARRANTY: (I) THAT THE SERVICE WILL DETECT, BLOCK OR PREVENT ALL
                SECURITY BREACHES OR THREATS, VIRUSES, SPAM OR OTHER HARMFUL OR
                UNWANTED CODE OR INTRUSIONS; AND (II) THAT THE SERVICE WILL
                PREVENT ANY CYBER THREATS AND/OR ATTACKS.
              </li>
              <li>
                ANY OUTCOME OF THE SERVICE DO NOT CONSTITUTE LEGAL OR OTHER
                ADVICE, AND YOU UNDERSTAND THAT YOU MUST DETERMINE FOR YOURSELF
                THE NEED TO OBTAIN YOUR OWN INDEPENDENT LEGAL OR OTHER ADVICE
                REGARDING THE SUBJECT MATTER OF ANY REPORT. YOUR USE OF AND
                RELIANCE UPON THE SERVICE AND/OR WEBSITE AND/OR THE SERVICE
                RESULTS IS ENTIRELY AT YOUR SOLE DISCRETION AND RISK, AND CYBER
                PRO AND ANYONE ON ITS BEHALF SHALL HAVE NO RESPONSIBILITY OR
                LIABILITY WHATSOEVER TO YOU IN CONNECTION WITH ANY OF THE
                FOREGOING.
              </li>
              <li>
                YOU AGREE THAT WE WILL NOT BE HELD RESPONSIBLE FOR ANY
                CONSEQUENCES THAT MAY RESULT FROM TECHNICAL PROBLEMS INCLUDING
                WITHOUT LIMITATION IN CONNECTION WITH THE INTERNET (SUCH AS SLOW
                CONNECTIONS, TRAFFIC CONGESTION OR OVERLOAD OF OUR OR OTHER
                SERVERS) OR ANY TELECOMMUNICATIONS OR INTERNET PROVIDERS.
              </li>
              <li>
                Applicable law may not allow the exclusion of certain
                warranties, so to that extent such exclusions may not apply.
              </li>
            </ul>
          </li>
          <li>
            <strong>Limitation of Liability</strong>. IN NO EVENT SHALL CYBER
            PRO, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS
            AND REPRESENTATIVES, OTHER THIRD PARTIES, AND EACH OF THEIR
            RESPECTIVE SUCCESSORS AND ASSIGNS, BE LIABLE FOR ANY INDIRECT,
            SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE CLAIMS, LOSSES, OR
            DAMAGES, RELATED TO OR IN CONNECTION WITH THE WEBSITE OR ANY SERVICE
            OR CONTENT MADE AVAILABLE ON OR THROUGH THE WEBSITE OR THE SERVICE,
            EVEN IF INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING BUT
            NOT LIMITED TO ANY LOSS OF PROFITS, BUSINESS, OR ANTICIPATED
            SAVINGS, ANY LOSS OF, OR DAMAGE TO DATA, REPUTATION, REVENUE OR
            GOODWILL AND/OR THE COST OF PROCURING ANY SUBSTITUTE GOODS OR
            SERVICES. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, CYBER
            PRO, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS
            AND REPRESENTATIVES SHALL NOT BE LIABLE FOR ANY CLAIMS, LOSSES, OR
            DAMAGES IN CONNECTION WITH ERRORS OR OMISSIONS CONTAINED IN OR
            ACCESSIBLE THROUGH THE WEBSITE OR SERVICES.
          </li>
        </ol>
        <p style={{ textAlign: "left" }}>
          IN NO EVENT SHALL THE AGGREGATE LIABILITY OF CYBER PRO, ITS DIRECTORS,
          OFFICERS, EMPLOYEES, AGENTS, OR ITS THIRD-PARTY PROVIDERS, UNDER, OR
          OTHERWISE IN CONNECTION WITH, THESE TERMS (INCLUDING THE WEBSITE AND
          THE SERVICE), EXCEED THE TOTAL AMOUNT OF FEES ACTUALLY PAID BY YOU (IF
          ANY) FOR IN THE THREE (3) MONTHS IMMEDIATELY PRIOR TO THE EVENT GIVING
          RISE TO SUCH LIABILITY.
        </p>
        <p style={{ textAlign: "left" }}>
          THE FOREGOING EXCLUSIONS AND LIMITATIONS ON LIABILITY SET FORTH IN
          THIS SECTION Limitation <strong>of Liability</strong>. IN NO EVENT
          SHALL CYBER PRO, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE
          PROVIDERS AND REPRESENTATIVES, OTHER THIRD PARTIES, AND EACH OF THEIR
          RESPECTIVE SUCCESSORS AND ASSIGNS, BE LIABLE FOR ANY INDIRECT,
          SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE CLAIMS, LOSSES, OR
          DAMAGES, RELATED TO OR IN CONNECTION WITH THE WEBSITE OR ANY SERVICE
          OR CONTENT MADE AVAILABLE ON OR THROUGH THE WEBSITE OR THE SERVICE,
          EVEN IF INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING BUT NOT
          LIMITED TO ANY LOSS OF PROFITS, BUSINESS, OR ANTICIPATED SAVINGS, ANY
          LOSS OF, OR DAMAGE TO DATA, REPUTATION, REVENUE OR GOODWILL AND/OR THE
          COST OF PROCURING ANY SUBSTITUTE GOODS OR SERVICES. WITHOUT LIMITING
          THE GENERALITY OF THE FOREGOING, CYBER PRO, ITS DIRECTORS, OFFICERS,
          EMPLOYEES, AGENTS, SERVICE PROVIDERS AND REPRESENTATIVES SHALL NOT BE
          LIABLE FOR ANY CLAIMS, LOSSES, OR DAMAGES IN CONNECTION WITH ERRORS OR
          OMISSIONS CONTAINED IN OR ACCESSIBLE THROUGH THE WEBSITE OR SERVICES.
          SHALL APPLY: (I) EVEN IF CYBER PRO, ITS AFFILIATES OR THIRD-PARTY
          PROVIDERS, HAVE BEEN ADVISED, OR SHOULD HAVE BEEN AWARE, OF THE
          POSSIBILITY OF LOSSES OR DAMAGES; (II) EVEN IF ANY REMEDY IN THESE
          TERMS FAILS OF ITS ESSENTIAL PURPOSE; AND (III) REGARDLESS OF THE
          THEORY OR BASIS OF LIABILITY (SUCH AS, BUT NOT LIMITED TO, BREACH OF
          CONTRACT OR TORT).
        </p>
        <p style={{ textAlign: "left" }}>
          NO ACTION, REGARDLESS OF FORM, MAY BE BROUGHT BY YOU AFTER THE EARLIER
          OF (A) 12 MONTHS AFTER THE DATE ON WHICH YOU BECOME AWARE THAT A CAUSE
          OF ACTION HAS ARISEN, OR (B) THE PERIOD SET FORTH UNDER THE APPLICABLE
          STATUTE OF LIMITATIONS.
        </p>
        <ol>
          <li></li>

          <li style={{ textAlign: "left" }}>
            <strong>Indemnification by Client</strong>. Client shall indemnify,
            defend and hold harmless Cyber Pro, its affiliates and its and their
            respective officers, directors and employees from and against any
            and all third-party claims, damages, actions and causes of action in
            connection with the Service, or in connection with any distribution,
            publication, exportation, disclosure, misuse or misconduct by
            Client, or fraudulent behavior by Client, with respect to Reports.
          </li>
          <li style={{ textAlign: "left" }}>
            <strong>Modifications</strong>{" "}
            <strong>to Website/Service/Content</strong>. You acknowledge and
            agree that Cyber Pro reserves the right to change, modify, amend,
            suspend or discontinue any aspect of the Website and Service or
            Content at any time, without notice and without liability to you or
            any other third party. We will make an effort to inform you of
            substantial changes through the channels of communication generally
            used in such circumstances. If you do not agree to the new or
            different terms, you should not use and are free to discontinue
            using the Services.
          </li>
          <li style={{ textAlign: "left" }}>
            <strong>Termination</strong>. Cyber Pro may terminate your use of
            the Service or the agreement with you at any time and without prior
            written notice in any case you have breached these Terms or the term
            of the proposal or purchase order including in the event of delay in
            payment of any fees due under a purchase order. We shall not be
            liable to you or any third party for the termination of your use of
            or access to the Website and/or Service, or any portion thereof. Any
            provision of these Terms which is intended to survive termination
            shall survive termination of these Terms.
          </li>
          <li style={{ textAlign: "left" }}>
            <strong>Force Majeure</strong>. Cyber Pro shall not be liable for
            any unavailability of the Website or Services caused by a Force
            Majeure. <strong>“Force Majeure Event”</strong> means circumstances
            beyond our reasonable control, including, for example, an act of
            God, act of government, flood, fire, earthquake, natural disaster,
            civil unrest, acts of terror, acts of war, riots, military or
            national emergencies, government restrictions, strikes or other
            labor problems, electrical disturbances, lack of power supplies,
            denial of service for any reason and internet service provider
            failure or delay.
          </li>
          <li style={{ textAlign: "left" }}>
            <strong>Severability</strong>. If any provision of these Terms is
            held by a court of competent jurisdiction to be invalid or
            unenforceable, then such provision shall be enforced to the maximum
            extent permissible so as to affect the intent of these Terms, and
            the remainder of these Terms shall continue in full force and
            effect.
          </li>
          <li style={{ textAlign: "left" }}>
            <strong>Choice of Law and Venue</strong>. This Agreement shall be
            governed by and interpreted in accordance with laws of the State of
            Israel, without giving effect to any conflict of law provisions. The
            exclusive jurisdiction shall vest with the competent courts in the
            city of Tel Aviv-Yafo, Israel.
          </li>
          <li style={{ textAlign: "left" }}>
            <strong>General</strong>. (i) These Terms and the Privacy Policy
            represent the complete agreement concerning the Website between you
            and Cyber Pro. Concerning the Service, to the extent of any
            inconsistency or conflict between these Terms and a proposal or
            purchase order, these Terms shall prevail. (ii) Any preprinted terms
            or general terms on the back of any Client purchase order or other
            Client ordering documents shall have no effect. (iii) Cyber Pro’s
            obligation to provide the Services under the relevant proposal and
            purchase order is subject to timely payment of all fees under the
            purchase order. (iv) Section headings are provided for convenience
            only and have no substantive effect on construction. (v) The failure
            of Cyber Pro to exercise or enforce any right or provision of these
            Terms will not be deemed a waiver of such right or provision. (vi)
            These Terms may not be assigned by Client without our prior written
            consent.
          </li>
        </ol>

        <ol></ol>
      </div>
    </div>
  );
}

export default TermsOfUse;
